# Generated by Django 4.0.6 on 2022-08-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0002_student_user_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='opened',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
