# Generated by Django 4.0.6 on 2022-08-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_theme_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(max_length=4095, verbose_name='Условие'),
        ),
    ]
